# Rescue DAG file, created after running
#   the Cats_and_Dogs-0.dag DAG file
# Created 8/25/2020 20:40:08 UTC
# Rescue DAG version: 2.0.1 (partial)
#
# Total number of Nodes: 29
# Nodes premarked DONE: 7
# Nodes that failed: 1
#   preprocess1_py_ID0000001,<ENDLIST>

DONE create_dir_Cats_and_Dogs_0_local
RETRY create_dir_Cats_and_Dogs_0_local 1
DONE stage_in_remote_local_2_0
RETRY stage_in_remote_local_2_0 1
DONE stage_in_remote_local_1_0
RETRY stage_in_remote_local_1_0 1
DONE stage_in_remote_local_0_0
RETRY stage_in_remote_local_0_0 1
DONE stage_in_local_local_0_0
RETRY stage_in_local_local_0_0 1
DONE stage_in_remote_local_4_0
RETRY stage_in_remote_local_4_0 1
DONE stage_in_remote_local_3_0
RETRY stage_in_remote_local_3_0 1
RETRY preprocess1_py_ID0000001 1
RETRY Augmentation_py_ID0000002 1
RETRY clean_up_local_level_3_0 1
RETRY stage_out_local_local_0_0 1
RETRY Data_Split_py_ID0000003 1
RETRY stage_out_local_local_1_0 1
RETRY register_local_0_0 1
RETRY clean_up_local_level_4_0 1
RETRY stage_out_local_local_2_0 1
RETRY VGG_model_py_ID0000004 1
RETRY register_local_1_0 1
RETRY clean_up_local_level_5_0 1
RETRY register_local_2_0 1
RETRY Optuna_py_ID0000005 1
RETRY stage_out_local_local_3_0 1
RETRY clean_up_local_level_6_0 1
RETRY stage_out_local_local_4_0 1
RETRY register_local_3_0 1
RETRY clean_up_local_level_7_0 1
RETRY register_local_4_0 1
RETRY clean_up_local_level_8_0 1
RETRY cleanup_Cats_and_Dogs_0_local 1
